name: Test and deploy test image to docker registry

on:
  push:
    branches:
      - test-server

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Dagger
        uses: dagger/dagger-for-github@v2
        with:
          install-only: true
      
      - name: Init Buildx
        run: |
          docker buildx create --name kdr-integration
          docker buildx inspect --bootstrap kdr-integration

      - name: Init Dagger
        run: dagger project init

      - name: Init Dependencies
        run: dagger project update

      - name: Do Tests
        env: 
          CRI_URL: ${{ secrets.CRI_URL }}
          CRI_USERNAME: ${{ secrets.CRI_USERNAME }}
          CRI_SECRET: ${{ secrets.CRI_SECRET }}
        run: dagger do deployTestImage